# Generated by Django 2.1.4 on 2019-08-21 03:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('course_code', models.CharField(max_length=5)),
                ('attendance', models.CharField(max_length=1)),
                ('topic', models.CharField(default='', max_length=80)),
                ('no_of_classes', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=1)),
                ('if_mod', models.BooleanField(default=False)),
                ('reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentProfile')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('faculty_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('EIE', 'EIE'), ('ME', 'ME'), ('CE', 'CE'), ('SH', 'SH')], max_length=4)),
            ],
        ),
    ]
