# Generated by Django 2.2 on 2019-08-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('EIE', 'EIE'), ('ME', 'ME'), ('CE', 'CE'), ('SH', 'SH')], max_length=4),
        ),
    ]
