# Generated by Django 2.2 on 2019-08-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_auto_20190802_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='topic',
            field=models.CharField(default='', max_length=80),
        ),
    ]
