# Generated by Django 2.1.4 on 2019-08-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_attendance_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='no_of_classes',
            field=models.IntegerField(default=1),
        ),
    ]
