# Generated by Django 2.2 on 2019-05-06 04:01

import HOD.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hod_credential',
            fields=[
                ('hod_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=64, unique=True)),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('EIE', 'EIE'), ('CE', 'CE'), ('ME', 'ME')], default='CSE', max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester_wise_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('EIE', 'EIE'), ('CE', 'CE'), ('ME', 'ME')], default='CSE', max_length=3)),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('courses', models.CharField(default='', max_length=53)),
            ],
        ),
        migrations.CreateModel(
            name='Course_allot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default=HOD.models.this_year, max_length=4)),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('EIE', 'EIE'), ('CE', 'CE'), ('ME', 'ME')], default='CSE', max_length=3)),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOD.Course')),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.FacultyProfile')),
            ],
        ),
    ]
