# Generated by Django 2.1.4 on 2019-07-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOD', '0002_semester_wise_course_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='elective',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='semester_wise_course',
            name='elective_courses',
            field=models.CharField(default='', max_length=17),
        ),
    ]
