# Generated by Django 2.1.4 on 2019-07-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOD', '0003_auto_20190721_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester_wise_mandatory_courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('EIE', 'EIE'), ('CE', 'CE'), ('ME', 'ME')], default='CSE', max_length=3)),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('courses', models.CharField(default='', max_length=53)),
            ],
        ),
    ]
