# Generated by Django 2.1.4 on 2019-07-21 21:10

import HOD.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOD', '0004_semester_wise_mandatory_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester_wise_electives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('EIE', 'EIE'), ('CE', 'CE'), ('ME', 'ME')], default='CSE', max_length=3)),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('elective_courses', models.CharField(default='', max_length=17)),
                ('year', models.CharField(default=HOD.models.this_year, max_length=4)),
            ],
        ),
        migrations.DeleteModel(
            name='Semester_wise_mandatory_courses',
        ),
        migrations.RemoveField(
            model_name='semester_wise_course',
            name='elective_courses',
        ),
        migrations.RemoveField(
            model_name='semester_wise_course',
            name='year',
        ),
    ]
